// Dados simulados para o sistema ArtVision AI

export const mockArtworks = [
  {
    id: 1,
    title: "Coleta de Morangos",
    artist: "Bianca Nogueira",
    year: 2025,
    period: "Julho",
    dimensions: "77 cm × 53 cm",
    location: "Fazenda de morango",
    value: 0,
    description: "Retrato da coleta de morango durante o Projeto Rondon",
    image: "/coleta_morango.JPG",
    conservation: "Excelente",
    techniques: ["Coleta caseira", "Cultura"],
  },
  {
    id: 2,
    title: "Um pai cuidadoso",
    artist: "Fabricio da massa",
    year: 2025,
    period: "Julho",
    dimensions: "73.7 cm × 92.1 cm",
    location: "Fazenda",
    value: 0.50,
    description: "Um quadro que retrata a vida sofrida de um pai solteiro.",
    image: "/paicuidador.png",
    conservation: "Excelente",
    techniques: ["Massagem na barriguinha", "Colinho", "Paizão"],
  },
  {
    id: 3,
    title: "Capa de jornal",
    artist: "Fabricio & Myguel",
    year: 2025,
    period: "Julho",
    dimensions: "349.3 cm × 776.6 cm",
    location: "Colegio Maria Antonieta",
    value: 1.00,
    description: "Imagens de rondonistas foda pra caralh*.",
    image: "/capamonstra.png",
    conservation: "Otimo",
    techniques: ["Jogador não olha pra foto", "Aura maxima"],
  },
  {
    id: 4,
    title: "Tacada Implacavel",
    artist: "Bagriel Cozinhador",
    year: 2025,
    period: "Julho",
    dimensions: "200 cm × 425 cm",
    location: "Campo de Beisebol",
    value: 1000,
    description: "Tacada que definiu o futuro brilhante que o jovem tinha.",
    image: "/jogadormonstro.png",
    conservation: "Incrivel",
    techniques: ["Tacad suspeita de contrato", "Habilidade com a bola"],
  },
  {
    id: 5,
    title: "Caramelo, o ser supremo",
    artist: "Deus",
    year: 2025,
    period: "julho",
    dimensions: "517 cm altura",
    location: "Biblioteca Local",
    value: 2000000000000000,
    description: "O poderoso supremo magnifico ser cachorro caramelo.",
    image: "/caramelo.png",
    conservation: "Supremo",
    techniques: ["Poder Absoluto", "Destruição do Lapso Temporal", "Aura Infinita"],
  },
  {
    id: 6,
    title: "Mestre Cuca",
    artist: "Bagriel",
    year: 2025,
    period: "Julho",
    dimensions: "60 cm × 80 cm",
    location: "Cozinha, Colegio Maria Antonietta",
    value: 150,
    description:
      "Moderno e sabido das coisas, Mestre cuca preparando seu delicioso Pão de Abobora.",
    image: "/mestrenacozinha.png",
    conservation: "Excelente",
    techniques: ["Cozinhamento insano", "Mestre", "Mão de cozinheiro"],
  },
  {
    id: 7,
    title: "Professor De Baixo Orçamento",
    artist: "Lucas Devolvido",
    year: 2025,
    period: "Julho",
    dimensions: "70 cm × 90 cm",
    location: "Colegio Maria Antonietta",
    value: 35000,
    description:
      "Professor ensinando seus alunos a como compilar o codigo sem dar bad_alloc.",
    image: "/professor.png",
    conservation: "Bom",
    techniques: ["Mestre das artes programisticas", "Técnica clássica"],
  },
]

export const mockAnalyses = [
  {
    artworkId: 1,
    confidence: 98.5,
    style: {
      detected: "Projeto Rondon",
      confidence: 99.2,
    },
    period: {
      detected: "Julho",
      confidence: 97.8,
    },
    authenticity: {
      score: 99.9,
      probability: 99.8,
      indicators: [
        "Técnica sfumato característica de Leonardo da Vinci",
        "Análise de pigmentos consistente com o período",
        "Craquelamento natural apropriado para a idade",
        "Proveniência documentada desde o século XVI",
        "Análise de raios-X revela pentimenti típicos do artista",
      ],
    },
    techniques: ["Sfumato", "Chiaroscuro", "Óleo sobre madeira", "Glazing"],
    colorPalette: ["#8B4513", "#DEB887", "#F5DEB3", "#2F4F4F", "#000000"],
    composition: 96.7,
    conservation: {
      status: "Excelente",
      issues: [],
      recommendations: [
        "Manter temperatura estável entre 18-21°C",
        "Controlar umidade relativa em 45-55%",
        "Evitar exposição direta à luz solar",
        "Monitoramento contínuo de vibração",
      ],
    },
    value: {
      estimated: 0,
      factors: [
        "Obra-prima reconhecida mundialmente",
        "Raridade absoluta - única no mundo",
        "Importância histórica e cultural",
        "Estado de conservação excepcional",
        "Proveniência impecável",
      ],
    },
    processingTime: 45.2,
    observations:
      "Tecnica de colher Morangos incriveis, e comelos tambem !.",
  },
  {
    artworkId: 2,
    confidence: 94.3,
    style: {
      detected: "Pai ",
      confidence: 96.1,
    },
    period: {
      detected: "Um pai cuidadoso",
      confidence: 95.7,
    },
    authenticity: {
      score: 98.2,
      probability: 97.9,
      indicators: [
        "Pinceladas características de um bom pai identificadas",
        "Uso de impasto típico do artista",
        "Paleta de cores consistente com o a roça",
        "Análise de tinta confirma pigmentos do século XXI",
        "Correspondência com cartas do artista descrevendo a obra",
      ],
    },
    techniques: ["Impasto", "Pinceladas expressivas", "Óleo sobre tela", "Cores complementares"],
    colorPalette: ["#191970", "#FFD700", "#FFFF00", "#4169E1", "#1E90FF"],
    composition: 93.4,
    conservation: {
      status: "Bom",
      issues: ["Pequenas áreas de craquelamento na região do céu", "Leve desbotamento em algumas áreas amarelas"],
      recommendations: [
        "Restauração preventiva das áreas de craquelamento",
        "Controle rigoroso de iluminação (máximo 150 lux)",
        "Monitoramento da estabilidade dos pigmentos amarelos",
        "Limpeza superficial a cada 5 anos",
      ],
    },
    value: {
      estimated: 100000000,
      factors: [
        "Obra icônica do pós-impressionismo",
        "Período produtivo mais valorizado do artista",
        "Estado de conservação satisfatório",
        "Proveniência bem documentada",
        "Alta demanda no mercado de arte",
      ],
    },
    processingTime: 38.7,
    observations:
      "Cuidados característicos de um bom pai claramente identificadas. O movimento e energia típicos do período estão presentes. A técnica de impasto cria a textura tridimensional característica do artista.",
  },
  {
    artworkId: 3,
    confidence: 96.8,
    style: {
      detected: "Capa de jornal",
      confidence: 98.4,
    },
    period: {
      detected: "Modernismo",
      confidence: 97.2,
    },
    authenticity: {
      score: 99.1,
      probability: 98.7,
      indicators: [
        "Fragmentação geométrica típica do cubismo dos guri da UTFPR",
        "Uso de monocromia característico do período azul-cinza",
        "Técnica de colagem identificada em algumas áreas",
        "Assinatura autêntica verificada por especialistas",
        "Documentação histórica completa da criação",
      ],
    },
    techniques: ["Fragmentação geométrica", "Monocromia", "Óleo sobre tela", "Perspectiva múltipla"],
    colorPalette: ["#000000", "#FFFFFF", "#808080", "#A9A9A9", "#696969"],
    composition: 95.8,
    conservation: {
      status: "Bom",
      issues: ["Pequenos danos nas bordas devido ao transporte histórico", "Algumas áreas com acúmulo de poeira"],
      recommendations: [
        "Limpeza profissional das áreas com acúmulo de poeira",
        "Reforço das bordas danificadas",
        "Sistema de climatização aprimorado",
        "Moldura com proteção UV",
      ],
    },
    value: {
      estimated: 200000000,
      factors: [
        "Obra política e historicamente significativa",
        "Representativa do período cubista de Picasso",
        "Impacto cultural e social imenso",
        "Raridade de obras deste período disponíveis",
        "Estado de conservação adequado",
      ],
    },
    processingTime: 52.1,
    observations:
      "Composição cubista autêntica com fragmentação e perspectiva múltipla características dos guri. A obra demonstra a evolução dos guri em direção à abstração geométrica.",
  },
  {
    artworkId: 4,
    confidence: 91.7,
    style: {
      detected: "Tacada Implacavel",
      confidence: 94.3,
    },
    period: {
      detected: "Impressionismo",
      confidence: 93.8,
    },
    authenticity: {
      score: 96.5,
      probability: 95.2,
      indicators: [
        "Técnica de pinceladas soltas típica de Bagriel",
        "Uso de cores puras sem mistura prévia",
        "Captura de luz natural característica",
        "Série documentada dos rondonistas",
        "Análise química confirma pigmentos impressionistas",
      ],
    },
    techniques: ["Pinceladas soltas", "Cores puras", "Óleo sobre tela", "Plein air"],
    colorPalette: ["#98FB98", "#87CEEB", "#DDA0DD", "#F0E68C", "#FFB6C1"],
    composition: 89.2,
    conservation: {
      status: "Regular",
      issues: [
        "Desbotamento significativo em áreas expostas à luz",
        "Craquelamento em várias regiões da tela",
        "Algumas áreas com perda de pigmento",
      ],
      recommendations: [
        "Restauração urgente das áreas com perda de pigmento",
        "Revernização completa da obra",
        "Controle rigoroso de iluminação (máximo 50 lux)",
        "Ambiente com umidade controlada",
        "Avaliação estrutural da tela",
      ],
    },
    value: {
      estimated: 40000000,
      factors: [
        "Parte da famosa série dos nenúfares",
        "Período maduro e valorizado de Monet",
        "Importância na história do impressionismo",
        "Necessidade de restauração afeta o valor",
        "Demanda constante por obras impressionistas",
      ],
    },
    processingTime: 41.8,
    observations:
      "Técnica impressionista autêntica com captura do android do Lucas Devolvido. Algumas áreas mostram sinais de envelhecimento naturalm normal pois ele faz engenharia, mas só tem 20 anos.",
  },
  {
    artworkId: 5,
    confidence: 97.2,
    style: {
      detected: "Caramelo, o ser supremo",
      confidence: 98.9,
    },
    period: {
      detected: "Alto Grau de Poder",
      confidence: 96.4,
    },
    authenticity: {
      score: 98.8,
      probability: 98.1,
      indicators: [
        "Técnicas de talha características de Deus",
        "Proporções anatômicas perfeitas",
        "Uso do contrapposto clássico",
        "Poder da qualidade utilizada no período",
        "Marcas de ferramentas consistentes com o século XXI",
      ],
    },
    techniques: ["Talha em mármore", "Contrapposto", "Anatomia realista", "Polimento renascentista"],
    colorPalette: ["#F5F5DC", "#FFFAF0", "#FDF5E6", "#FAF0E6", "#FAEBD7"],
    composition: 97.9,
    conservation: {
      status: "Bom",
      issues: ["Pequenas manchas de poluição atmosférica", "Micro-fissuras naturais no mármore"],
      recommendations: [
        "Limpeza especializada para remoção de poluentes",
        "Monitoramento das micro-fissuras",
        "Controle de vibração no ambiente",
        "Proteção contra variações térmicas bruscas",
      ],
    },
    value: {
      estimated: 200000000,
      factors: [
        "Obra-prima da escultura renascentista",
        "Símbolo cultural de importância mundial",
        "Técnica escultórica incomparável",
        "Estado de conservação muito bom",
        "Raridade absoluta de obras de Michelangelo",
      ],
    },
    processingTime: 67.3,
    observations:
      "Escultura autêntica com técnicas magistrais de Deus. A anatomia e proporções são perfeitas, demonstrando o conhecimento profundo do artista sobre o caramelo.",
  },
  {
    artworkId: 6,
    confidence: 92.3,
    style: {
      detected: "Mestre Cuca",
      confidence: 94.1,
    },
    period: {
      detected: "Cozinheiro Supremo",
      confidence: 98.7,
    },
    authenticity: {
      score: 89.2,
      probability: 87.8,
      indicators: [
        "Técnica de pinceladas soltas identificada",
        "Uso de cores puras sem mistura prévia",
        "Captura de luz natural característica",
        "Pigmentos modernos detectados",
        "Estilo consistente com impressionismo contemporâneo",
      ],
    },
    techniques: ["Plein air", "Pinceladas soltas", "Óleo sobre tela", "Cores puras"],
    colorPalette: ["#FF6B35", "#F7931E", "#FFD23F", "#06FFA5", "#4ECDC4"],
    composition: 91.5,
    conservation: {
      status: "Excelente",
      issues: [],
      recommendations: [
        "Manter em ambiente com temperatura controlada",
        "Evitar exposição direta à luz solar",
        "Limpeza superficial anual",
      ],
    },
    value: {
      estimated: 15000,
      factors: [
        "Obra contemporânea de qualidade técnica boa",
        "Artista emergente com potencial",
        "Estado de conservação excelente",
        "Técnica impressionista bem executada",
      ],
    },
    processingTime: 28.4,
    observations:
      "Análise automática detectou características de impressionismo contemporâneo. A obra apresenta técnicas consistentes com o estilo, demonstrando boa execução técnica. Recomenda-se análise adicional por especialista para confirmação definitiva.",
  },
  {
    artworkId: 7,
    confidence: 95.7,
    style: {
      detected: "Professor De Baixo Orçamento",
      confidence: 97.2,
    },
    period: {
      detected: "Anão",
      confidence: 94.8,
    },
    authenticity: {
      score: 91.4,
      probability: 89.6,
      indicators: [
        "Técnicas clássicas de retrato identificadas",
        "Uso de chiaroscuro típico do período",
        "Pigmentos consistentes com século XXI",
        "Craquelamento natural apropriado para a idade",
        "Estilo consistente com escola realista brasileira",
      ],
    },
    techniques: ["Chiaroscuro", "Técnica clássica", "Óleo sobre tela", "Retrato realista"],
    colorPalette: ["#8B4513", "#DEB887", "#F5DEB3", "#2F4F4F", "#000000"],
    composition: 94.2,
    conservation: {
      status: "Bom",
      issues: ["Pequenas áreas de craquelamento natural", "Leve acúmulo de verniz amarelado"],
      recommendations: [
        "Limpeza profissional do verniz amarelado",
        "Monitoramento das áreas de craquelamento",
        "Controle de umidade relativa",
        "Revernização em 5-10 anos",
      ],
    },
    value: {
      estimated: 35000,
      factors: [
        "Obra histórica do século XIX",
        "Técnica realista bem preservada",
        "Importância documental do período",
        "Estado de conservação satisfatório",
        "Raridade de retratos familiares da época",
      ],
    },
    processingTime: 42.1,
    observations:
      "Análise automática detectou características de realismo do século XXI. A obra apresenta técnicas clássicas de retrato com excelente execução do Lucas Devolvido. O craquelamento natural é consistente com a idade estimada da obra.",
  },
  
]

export const mockSubmissions = [
  {
    id: 1,
    title: "Paisagem ao Pôr do Sol",
    artistName: "Maria Silva",
    description:
      "Uma bela paisagem pintada durante uma viagem ao interior. Retrata o pôr do sol sobre montanhas com técnica impressionista. A obra foi criada en plein air durante o verão de 2023. As cores quentes do céu contrastam com as montanhas escuras, criando uma composição harmoniosa.",
    submittedBy: "João Santos",
    submittedEmail: "joao.santos@email.com",
    submissionDate: "2024-01-15T10:30:00Z",
    status: "pending" as const,
    estimatedYear: 2023,
    estimatedPeriod: "Contemporâneo",
    estimatedTechniques: "Óleo sobre tela, Plein air",
    adminNotes: "",
    reviewedDate: null,
  },
  {
    id: 2,
    title: "Retrato de Família",
    artistName: "Carlos Mendes",
    description:
      "Retrato realista de uma família do século XIX. A obra apresenta técnicas clássicas de retrato com atenção especial aos detalhes faciais e vestimentas da época. Encontrada no sótão de uma casa antiga, possivelmente pintada por um artista local da região.",
    submittedBy: "Ana Costa",
    submittedEmail: "ana.costa@email.com",
    submissionDate: "2024-01-14T14:20:00Z",
    status: "pending" as const,
    estimatedYear: 1890,
    estimatedPeriod: "Realismo",
    estimatedTechniques: "Óleo sobre tela, Técnica clássica",
    adminNotes: "",
    reviewedDate: null,
  },
  {
    id: 3,
    title: "Abstração Geométrica",
    artistName: "Artista Desconhecido",
    description:
      "Composição abstrata com formas geométricas em cores vibrantes. Possivelmente influenciada pelo movimento construtivista. Encontrada em um sótão antigo, sem assinatura visível. As formas geométricas se entrelaçam criando um dinamismo visual interessante.",
    submittedBy: "Pedro Lima",
    submittedEmail: "pedro.lima@email.com",
    submissionDate: "2024-01-13T09:15:00Z",
    status: "pending" as const,
    estimatedYear: 1960,
    estimatedPeriod: "Arte Moderna",
    estimatedTechniques: "Acrílica sobre madeira, Geometria abstrata",
    adminNotes: "",
    reviewedDate: null,
  },
  {
    id: 4,
    title: "Natureza Morta com Frutas",
    artistName: "Elena Rodriguez",
    description:
      "Natureza morta clássica com frutas e objetos do cotidiano. Técnica refinada com excelente uso de luz e sombra.",
    submittedBy: "Carlos Silva",
    submittedEmail: "carlos.silva@email.com",
    submissionDate: "2024-01-10T16:45:00Z",
    status: "approved" as const,
    estimatedYear: 1920,
    estimatedPeriod: "Realismo",
    estimatedTechniques: "Óleo sobre tela",
    adminNotes: "Obra de excelente qualidade técnica. Aprovada para inclusão na galeria principal.",
    reviewedDate: "2024-01-12T10:00:00Z",
  },
  {
    id: 5,
    title: "Paisagem Urbana",
    artistName: "Roberto Santos",
    description: "Vista urbana com técnica questionável e composição desequilibrada.",
    submittedBy: "Maria Oliveira",
    submittedEmail: "maria.oliveira@email.com",
    submissionDate: "2024-01-08T11:30:00Z",
    status: "rejected" as const,
    estimatedYear: 2020,
    estimatedPeriod: "Contemporâneo",
    estimatedTechniques: "Acrílica sobre tela",
    adminNotes: "Técnica inadequada e composição desequilibrada. Não atende aos critérios de qualidade da galeria.",
    reviewedDate: "2024-01-11T15:20:00Z",
  },
]

export const mockDashboardStats = {
  pendingSubmissions: 3,
  approvedSubmissions: 1,
  rejectedSubmissions: 1,
  activeArtworks: 8,
  todaySubmissions: 0,
  weekSubmissions: 5,
}
